package net.notfab.ttvsi.common;

public enum NetEvent {

    CLIENT_POLL_PROGRESS,
    CLIENT_POLL_FINISHED,
    CLIENT_CREATE_POLL,
    CLIENT_CREATE_REWARD,
    CLIENT_DELETE_REWARD,
    CLIENT_UPDATE_REWARDS,

    SERVER_REWARD_SYNC,
    SERVER_ROOM_MEMBERS_SYNC,
    SERVER_POLL_FINISHED,
    SERVER_POLL_CREATE,
    SERVER_POLL_UPDATE,

    REWARD_REDEEMED

}
